<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DevOps</name>
   <tag></tag>
   <elementGuidId>33d106ff-8134-4f9e-856d-cdbfe10dba57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tt-ca07e99b-e07d-bb72-582f-b8e45b36abc6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tt-ca07e99b-e07d-bb72-582f-b8e45b36abc6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6f010aa-3bb8-4870-bffc-2b760aa0795f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>698efbfd-2c9b-4d39-8345-6216e492d969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tt-ca07e99b-e07d-bb72-582f-b8e45b36abc6</value>
      <webElementGuid>0f46fe25-5667-40d7-a09f-1bf38b01e490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tt-suggestion tt-selectable tt-cursor</value>
      <webElementGuid>b1b81857-6f2e-4351-bf9f-35bdcd2df43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevOps</value>
      <webElementGuid>5d5b9f2e-fcf3-4f41-baa4-7c858fc2c9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tt-ca07e99b-e07d-bb72-582f-b8e45b36abc6&quot;)</value>
      <webElementGuid>a7494c89-3946-4cbe-80aa-67ad86c4ed2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tt-ca07e99b-e07d-bb72-582f-b8e45b36abc6']</value>
      <webElementGuid>9379794a-52f2-43ee-ac1c-b376c8b8a7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Activity_CHOICE_listbox']/div/div</value>
      <webElementGuid>4d975cec-984c-4d76-b102-7a765410776f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Votre activité'])[1]/following::div[4]</value>
      <webElementGuid>32e48315-4add-4051-b7c0-47a464c0754b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Véhicule de Tourisme avec Chauffeur'])[2]/following::div[5]</value>
      <webElementGuid>a2661e98-e09e-4deb-8039-4d810186669b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ops']/parent::*</value>
      <webElementGuid>ed2ac140-6684-4eab-b689-849c45f1d534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div</value>
      <webElementGuid>9c466c13-8d4d-4c1f-8674-876c11afa4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tt-ca07e99b-e07d-bb72-582f-b8e45b36abc6' and (text() = 'DevOps' or . = 'DevOps')]</value>
      <webElementGuid>50d28e7f-d607-416d-bbb0-29c4a57088da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
