<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DevOps_1</name>
   <tag></tag>
   <elementGuidId>eacf243e-3ebe-4809-92e5-747e1efc9069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tt-ab06d8bb-5bd2-1d3d-3437-0b894dabae44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tt-ab06d8bb-5bd2-1d3d-3437-0b894dabae44']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>259a559d-99fe-4d15-a3df-61245c31001a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>39c10716-8931-495d-9dbb-d0e72bf46392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tt-ab06d8bb-5bd2-1d3d-3437-0b894dabae44</value>
      <webElementGuid>27ebc4ff-394f-443b-9a40-392a2d873339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tt-suggestion tt-selectable tt-cursor</value>
      <webElementGuid>b83cb08d-05fa-4c76-a3ff-a559e07f31c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevOps</value>
      <webElementGuid>53ded3ca-5930-46e7-9e35-6f07d9c0a9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tt-ab06d8bb-5bd2-1d3d-3437-0b894dabae44&quot;)</value>
      <webElementGuid>1723c02a-0d34-48d9-8d95-9276779f4dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tt-ab06d8bb-5bd2-1d3d-3437-0b894dabae44']</value>
      <webElementGuid>e03112e2-e725-4483-93b4-2aa19a4e19a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Activity_CHOICE_listbox']/div/div</value>
      <webElementGuid>2f1cf2fd-93bb-4ccc-a2bf-66aabee61c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Votre activité'])[1]/following::div[4]</value>
      <webElementGuid>749ab85f-c255-4dcb-839e-5e712282ae66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Véhicule de Tourisme avec Chauffeur'])[2]/following::div[5]</value>
      <webElementGuid>6fdb1737-9aef-464f-bfc8-c7263909673a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ops']/parent::*</value>
      <webElementGuid>4b8b9a43-ba47-4002-b80c-09931a50e3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div</value>
      <webElementGuid>96a6084b-8cb6-4341-bc63-203903ad7e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tt-ab06d8bb-5bd2-1d3d-3437-0b894dabae44' and (text() = 'DevOps' or . = 'DevOps')]</value>
      <webElementGuid>5e2f3fa4-fd04-40ec-9100-5f92da546a6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
