<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Turnover_NUM--mdc</name>
   <tag></tag>
   <elementGuidId>e4caf7c1-8ba7-42ac-ae00-e92eb12dd6ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Turnover_NUM--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Turnover_NUM--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e07f0f6-3010-4eaa-a073-cee21204ca80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fa16b96-dffd-4d00-b10b-3e3dce4e6969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Turnover_NUM--mdc</value>
      <webElementGuid>bd258f31-b5f3-47de-a14d-1083fd66495c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Turnover_NUM--mdc-label</value>
      <webElementGuid>d89bb132-4f31-45d8-9a12-53c8fc0f9452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>57d422d7-e3f7-44c8-a90f-edba4c641879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]+([ ,][0-9]+)*</value>
      <webElementGuid>2a7a6270-d84d-46a9-9bf8-9137280b0eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Turnover_NUM--mdc&quot;)</value>
      <webElementGuid>fbd18367-7cd5-423b-b06e-40fc8639f642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Turnover_NUM--mdc']</value>
      <webElementGuid>d5424066-bf33-4ee4-b1e4-77ecfe8c5a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question118945']/div[3]/div/input</value>
      <webElementGuid>a819953f-06c7-43e5-bc33-e7dd5ea36606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3195f147-eb37-4f06-915d-1eb8e854f730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Turnover_NUM--mdc']</value>
      <webElementGuid>98e30725-2e1d-487f-b29d-cfdeb4c3f908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
