<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nom_LastName--mdc</name>
   <tag></tag>
   <elementGuidId>1d260a0a-35f9-449f-ba13-b4bac77dcfc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LastName--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LastName--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3be49206-7f02-4115-8373-47ac90f5c70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20b20edd-c071-4609-b90c-409669fb2674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LastName--mdc</value>
      <webElementGuid>d32a8ef7-c533-442c-8c56-e07057cf3cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>LastName--mdc-label</value>
      <webElementGuid>247dd959-d29f-494f-a8a6-57f6e4d290c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>4aa236d5-e5c0-451d-94d7-b0e192c141e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>f6d55fe6-17e6-4c2a-8cfd-802283185428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LastName--mdc&quot;)</value>
      <webElementGuid>b143d23f-fb0a-479f-8a15-22beebea79c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LastName--mdc']</value>
      <webElementGuid>fb08e520-7bde-479c-906e-33ed8875c926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question118957']/div[2]/div/div/div[2]/div[3]/div/input</value>
      <webElementGuid>630c40a2-518d-4f10-bf19-d2915761ccad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>dad17eb1-3686-4205-8ac6-69f9e71e49e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LastName--mdc']</value>
      <webElementGuid>675c3eeb-bc06-4920-9147-89de3fd158cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
