<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numro de tlphone professionnel_Teleph_534f19</name>
   <tag></tag>
   <elementGuidId>5423b2db-57db-4740-bae3-b9bfddeeb735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TelephoneNumber_NUM--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TelephoneNumber_NUM--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fd68a5d-8d88-4640-a32d-03b4217d867f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9c364bf-9614-4929-8beb-09b91120009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TelephoneNumber_NUM--mdc</value>
      <webElementGuid>8cadf22b-cf89-4152-a34a-170f5e816f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TelephoneNumber_NUM--mdc-label</value>
      <webElementGuid>ee43d095-c066-4bcf-ae60-91f7fa47831e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>e02a3fab-0f64-4103-bcae-740e1a461233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>97997737-3964-4858-8c2f-ba4b347cd09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TelephoneNumber_NUM--mdc&quot;)</value>
      <webElementGuid>3f3af383-675f-471f-83f5-d0a6c29bdde6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TelephoneNumber_NUM--mdc']</value>
      <webElementGuid>d503f987-8e18-4675-bd8b-5f9fc9185aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question118959']/div[3]/div/input</value>
      <webElementGuid>33286f36-baf3-4ecd-97bd-416fe65d9091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/input</value>
      <webElementGuid>ed7a25d5-d6ce-4f37-bb09-6be09cd459ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'TelephoneNumber_NUM--mdc']</value>
      <webElementGuid>a9ecd0fb-c224-45c3-9e2b-2967b1aea747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
