<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ville de lentreprise_CompanyCity_TXT--mdc</name>
   <tag></tag>
   <elementGuidId>1181d558-605c-4541-a014-950efe04face</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CompanyCity_TXT--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyCity_TXT--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce3d707-597d-47bc-9e0f-d45ee01ff9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04c081a9-4b50-4813-8958-274bacd7a1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyCity_TXT--mdc</value>
      <webElementGuid>2773f44b-994e-4bc9-abd3-363ebd6226f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CompanyCity_TXT--mdc-label</value>
      <webElementGuid>b6aa0ba9-088f-4427-947d-e5bf98e98559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>5c1ab1a8-7929-4a37-b634-051ddaa29b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyCity_TXT--mdc&quot;)</value>
      <webElementGuid>8c418724-882c-45e5-8dac-73ee8d85540e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyCity_TXT--mdc']</value>
      <webElementGuid>a43f923c-1e54-4b83-a1e4-950ef2f76f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question119054']/div[3]/div/input</value>
      <webElementGuid>4f52ace4-7ecb-4965-ac18-d5d3db03bf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/input</value>
      <webElementGuid>c04d979c-9dbb-4cc9-b37c-2b98aee6a832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CompanyCity_TXT--mdc']</value>
      <webElementGuid>5c8740fd-6f3d-4f02-b775-b58df867ed3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
