<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adresse de lentreprise_CompanyAddress_c6a232</name>
   <tag></tag>
   <elementGuidId>070b33e9-c7de-49ce-95fa-1c55a3c68102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CompanyAddressLine_TXT--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyAddressLine_TXT--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1327e479-495e-4f53-b5e6-d286eb4200c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ae3ba1a-707b-4593-aa5b-679ee53624ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyAddressLine_TXT--mdc</value>
      <webElementGuid>0e883db0-0edf-41f3-8f6d-ef78164b14ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CompanyAddressLine_TXT--mdc-label</value>
      <webElementGuid>42e0f32e-987d-439a-b530-257a0c72e178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>0f308331-c9d1-491e-ab37-1f0b50adc779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>street-address</value>
      <webElementGuid>2530db2f-5535-4e8a-a9ba-84582f0d1245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyAddressLine_TXT--mdc&quot;)</value>
      <webElementGuid>b568747d-fcf6-4a2e-9ab4-2c537977cee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyAddressLine_TXT--mdc']</value>
      <webElementGuid>2e22854d-67a2-4a10-84ff-a8dbb671d355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question119052']/div[3]/div/input</value>
      <webElementGuid>5dbd2203-5069-49d4-89fc-5c2a579a5398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[3]/div/input</value>
      <webElementGuid>2a5f9d5c-0ada-44d7-9390-675e2d4bb170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CompanyAddressLine_TXT--mdc']</value>
      <webElementGuid>453d838a-a7c6-4873-b9e0-6e66b59073fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
