<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Votre activit_Activity_CHOICE</name>
   <tag></tag>
   <elementGuidId>6607dca4-fdc7-42a9-9bf9-8a5b71ae7d60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Activity_CHOICE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Activity_CHOICE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe506e1-8050-42f9-a238-72bd52223af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Activity_CHOICE</value>
      <webElementGuid>e75c553a-b729-49b5-a5d2-5946bc39b3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a70340f8-7426-4030-a2fe-f78e574007de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>typeahead autocomplete form-control tt-input</value>
      <webElementGuid>0e26c617-37ac-4df2-a96b-34ca35d797f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Activity_CHOICE</value>
      <webElementGuid>12595436-c28b-47ea-b1eb-61b549c9cd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf29aed5-bf62-4df8-9351-8692b78f55b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c5e2a821-2ee5-4497-8227-4b4a184e47e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>Activity_CHOICE_listbox</value>
      <webElementGuid>8ab24fe2-5a1c-4608-a11b-ac0565b4013d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>213bcc25-e416-4176-afb6-87c874c58f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>76737f04-c451-481c-8d72-be61ac7d250c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db3f3671-17d2-4444-a2c1-a065c8940175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Activity_CHOICE&quot;)</value>
      <webElementGuid>e8178ddb-a6e6-45d4-a4c8-59b0ba9ed821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Activity_CHOICE']</value>
      <webElementGuid>d200d695-804e-47c4-b046-6de2dbc2b721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question119038']/div/div/div[5]/span/input[2]</value>
      <webElementGuid>fb07ec92-9d5a-4cf1-b463-36b07cdc7bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input[2]</value>
      <webElementGuid>0915df43-ea02-4298-a0bd-c5b3390d6a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Activity_CHOICE' and @type = 'text' and @name = 'Activity_CHOICE']</value>
      <webElementGuid>bb2655ec-8058-4497-be0e-4ec1ac791c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
