<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nom de lentreprise_CompanyName_TXT--mdc</name>
   <tag></tag>
   <elementGuidId>1e84c8b1-cb59-4fbc-a312-5a8d1725bb54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CompanyName_TXT--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyName_TXT--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3efa4bec-aae8-40b8-ae2c-4b4f75f0c305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3854f6a5-ad39-4b2c-a415-f07e9553755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyName_TXT--mdc</value>
      <webElementGuid>479e6d5b-b18b-4cb4-ba42-17bcef9de67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CompanyName_TXT--mdc-label</value>
      <webElementGuid>fccf9ab5-f271-4584-af2d-adf1f5a61202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>3bfc87e2-5cf6-40fb-a3e0-196b86c590bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>c5af085c-0a14-47b6-a01c-0176b7d91671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyName_TXT--mdc&quot;)</value>
      <webElementGuid>6d4daa95-b28b-4167-8885-3f894e32d176</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyName_TXT--mdc']</value>
      <webElementGuid>ec06a865-5adb-48c8-9410-2b5fd409eec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question118961']/div[3]/div/input</value>
      <webElementGuid>baa40c5d-ac87-465e-888c-c292f910e1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/input</value>
      <webElementGuid>b9e1f88a-5d8f-424c-9953-cbfb662e2fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CompanyName_TXT--mdc']</value>
      <webElementGuid>14c316fe-3156-45fc-a379-437cc8546962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
