<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Code postal de l, , entreprise_988b63</name>
   <tag></tag>
   <elementGuidId>64a73ca7-aa10-4a9a-99b4-08f1ab3bb2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CompanyPostcode_TXT--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CompanyPostcode_TXT--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d47f1b82-b4b9-40e8-8e20-3b4362e5adac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>715045ed-ccad-42d7-979f-bc4822f95f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyPostcode_TXT--mdc</value>
      <webElementGuid>ff978eb3-6b69-4aa7-b0e4-e1237b2891c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CompanyPostcode_TXT--mdc-label</value>
      <webElementGuid>9a08dfb2-268e-4934-8dc4-eabeecf2d9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>4c57046f-31b5-4702-85ff-7be7d2968ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>0f08c137-214d-44d9-886c-4ee0037361d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyPostcode_TXT--mdc&quot;)</value>
      <webElementGuid>14b287ca-7dbd-4834-b54d-614a929a2e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CompanyPostcode_TXT--mdc']</value>
      <webElementGuid>9b56d1d1-ceea-4766-99d8-80ae6916fa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question120495']/div[3]/div/input</value>
      <webElementGuid>ba08679e-2b8f-444b-b531-b160b008942e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div[3]/div/input</value>
      <webElementGuid>e40004f7-974e-4d0e-8c15-15f0c5fc4656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CompanyPostcode_TXT--mdc']</value>
      <webElementGuid>d921fa0d-005a-45b1-861c-71715da2b1f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
