<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email professionnel_Email_TXT--mdc</name>
   <tag></tag>
   <elementGuidId>7d8c7c4b-f140-40e7-ad4b-38c2251df7c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Email_TXT--mdc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Email_TXT--mdc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c1ab987-34f3-4c25-97f5-3d5ce74fbefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ce5640f-6d8c-42e4-94f1-9b57be57f3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Email_TXT--mdc</value>
      <webElementGuid>5e66f631-3975-4a6d-85af-6de48b06277d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Email_TXT--mdc-label</value>
      <webElementGuid>b1eead62-fd68-46a8-a3ac-2f982d30da0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-text-field__input</value>
      <webElementGuid>10b3f654-6045-4587-86c8-581aaca3d98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>57893e39-a5a1-4a4e-84e2-bc05dd001a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Email_TXT--mdc&quot;)</value>
      <webElementGuid>375a3516-6e27-4380-b2bd-a09114f2a71c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Email_TXT--mdc']</value>
      <webElementGuid>b5699669-0e01-457f-86de-9193eb4e09f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question118958']/div[3]/div/input</value>
      <webElementGuid>259a758b-4f0e-4d5a-aa9d-6ffb7e4f0573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/input</value>
      <webElementGuid>66151fc8-602e-4f10-b800-074e6f83adce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Email_TXT--mdc']</value>
      <webElementGuid>d9207cf1-7c6d-4a14-983b-441c148e3cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
