<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Informatique</name>
   <tag></tag>
   <elementGuidId>6b0c2f5a-c226-40b0-8802-b6f5119f9a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Sector_CHOICE--mdc']/ul/li[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>93521e0e-7242-4a92-addb-a29751dfd5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-list-item</value>
      <webElementGuid>d1a4e8d2-53e8-4c3e-8e62-5ac19110100c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Informatique</value>
      <webElementGuid>ded2c23f-94ad-4e08-b929-76b18b29dc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2bb18592-5318-429e-b270-a5aeae87f7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>37cf405b-f9a9-4312-9c8c-41b1a65e496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informatique</value>
      <webElementGuid>5533d531-406c-42d2-bcb1-f5fd72406d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Sector_CHOICE--mdc&quot;)/ul[@class=&quot;mdc-list&quot;]/li[@class=&quot;mdc-list-item&quot;]</value>
      <webElementGuid>51d48d76-cdd1-438e-b601-0e45d8d17dfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Sector_CHOICE--mdc']/ul/li[13]</value>
      <webElementGuid>950c9cf3-8e28-46c2-9803-6e2e040d03fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immobilier'])[2]/following::li[1]</value>
      <webElementGuid>694372d1-1c6d-4290-bd55-b47c77353bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hygiène, Santé, Beauté'])[2]/following::li[2]</value>
      <webElementGuid>7db87a28-5283-4eec-9108-449b1ce94199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Marché de l', &quot;'&quot;, 'art')])[2]/preceding::li[1]</value>
      <webElementGuid>df91e1d0-9765-4a80-9840-a215be49fe6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]</value>
      <webElementGuid>124c9650-60ae-403a-9b66-9f1e3b825204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Informatique' or . = 'Informatique')]</value>
      <webElementGuid>800ce1ea-db7c-4e31-867b-7c10b0849cca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
