<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Informatique</name>
   <tag></tag>
   <elementGuidId>82178e55-9824-4406-b95a-0dc1ca062238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Sector_CHOICE--mdc']/ul/li[13]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55f21e32-1d03-4f38-b750-e65dfcbb8913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-list-item__text</value>
      <webElementGuid>fee6ced1-1ab7-4061-8984-50804e748391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informatique</value>
      <webElementGuid>4ce0e96e-be16-484f-b9b1-b17bd84b9af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Sector_CHOICE--mdc&quot;)/ul[@class=&quot;mdc-list&quot;]/li[@class=&quot;mdc-list-item&quot;]/span[@class=&quot;mdc-list-item__text&quot;]</value>
      <webElementGuid>23299780-f047-409c-8add-9a6b4988cbcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Sector_CHOICE--mdc']/ul/li[13]/span</value>
      <webElementGuid>a8b19e7c-72a3-4e9a-b0f9-14a7f1ed77bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Immobilier'])[2]/following::span[1]</value>
      <webElementGuid>be6c9323-c259-4f01-af86-01c2f5eb7f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hygiène, Santé, Beauté'])[2]/following::span[2]</value>
      <webElementGuid>b373df9e-4309-464e-9a2a-1929b37a20ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Marché de l', &quot;'&quot;, 'art')])[2]/preceding::span[1]</value>
      <webElementGuid>abf9861f-a120-48a6-9e71-7585be54adfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing &amp; Communication'])[2]/preceding::span[2]</value>
      <webElementGuid>7985730d-cb08-4696-a418-80fad77f4bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/span</value>
      <webElementGuid>0994cfa5-790f-4e3b-8b61-fe442249de9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Informatique' or . = 'Informatique')]</value>
      <webElementGuid>921c578c-0348-44f5-8afb-4ecba05b50f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
