<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tape suivante</name>
   <tag></tag>
   <elementGuidId>6060eab5-f204-491a-98f9-efda0f192f78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='continueButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e22fd34-0ff9-4c09-acaa-d79abd54e98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bffcb979-db21-49ec-964d-166f5dcb7a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>continueButton</value>
      <webElementGuid>26401f51-84a2-4f5b-bf7b-75508d57db87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueButton</value>
      <webElementGuid>0273dcdd-2a4f-49de-801b-080452a1a0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>instanda-button instanda-quote-continue-button btn btn-primary</value>
      <webElementGuid>e84ac986-d160-4579-a358-14ac4852d596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Étape suivante </value>
      <webElementGuid>9d9c73eb-6ecd-4cf1-8c04-0409ae9b2d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueButton&quot;)</value>
      <webElementGuid>429ca55d-f781-4831-98cb-517008851438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='continueButton']</value>
      <webElementGuid>cd52125c-56af-4c84-9d06-29fa2fb2a829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quote-content-form']/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>f9ac09eb-58b7-4f7f-a553-8a09b9e81a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mettre à jour'])[1]/following::button[1]</value>
      <webElementGuid>a74c4b0e-4991-4510-bff6-bb3e72e3a390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Étape précédente'])[1]/following::button[2]</value>
      <webElementGuid>d99dd141-7fd8-4a5a-9fe5-49e2a4da5b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your session has expired, you will have to restart your quote'])[1]/preceding::button[1]</value>
      <webElementGuid>81f52872-e92f-4703-9e1d-a1b5ad4b0fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restart Quote'])[1]/preceding::button[1]</value>
      <webElementGuid>52db870e-af4d-468e-9f05-4b731f87dc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Étape suivante']/parent::*</value>
      <webElementGuid>a3335825-67ea-4685-83d2-c0005c349890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>597815b2-567f-443f-9d6d-b5e7ac107a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'continueButton' and @id = 'continueButton' and (text() = 'Étape suivante ' or . = 'Étape suivante ')]</value>
      <webElementGuid>4541c287-b199-43bd-8eca-6895ffc9174f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
